kind: pipeline
type: docker
name: default

steps:
- name: build
  image: node:17
  pull: if-not-exists
  commands:
  - npm install --legacy-peer-deps
  - npm run build
  when:
    event:
    - tag
- name: deploy
  image: plugins/npm
  pull: if-not-exists
  settings:
    username: overwrite
    password: overwrite
    token:
      from_secret: NPM_TOKEN
  when:
    event:
    - tag
